# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(369, 281)
        Dialog.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 240, 341, 32))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 30, 341, 20))
        self.label_11.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 11pt \"黑体\";")
        self.label_11.setObjectName("label_11")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(120, 130, 101, 21))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.lab_savefolder = QtWidgets.QLabel(Dialog)
        self.lab_savefolder.setGeometry(QtCore.QRect(110, 70, 251, 31))
        self.lab_savefolder.setStyleSheet("")
        self.lab_savefolder.setObjectName("lab_savefolder")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 71, 31))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 120, 81, 31))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 81, 31))
        self.label_4.setObjectName("label_4")
        self.lab_gameinstall_state = QtWidgets.QLabel(Dialog)
        self.lab_gameinstall_state.setGeometry(QtCore.QRect(90, 150, 281, 31))
        self.lab_gameinstall_state.setObjectName("lab_gameinstall_state")
        self.lab_game_path = QtWidgets.QLabel(Dialog)
        self.lab_game_path.setGeometry(QtCore.QRect(30, 180, 351, 21))
        self.lab_game_path.setObjectName("lab_game_path")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 200, 181, 51))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_11.setText(_translate("Dialog", "Hollow Knight(空洞骑士)存档修改器"))
        self.lab_savefolder.setText(_translate("Dialog", "Null"))
        self.label_2.setText(_translate("Dialog", "存档文件夹:"))
        self.label.setText(_translate("Dialog", "选择存档文件:"))
        self.label_4.setText(_translate("Dialog", "游戏位置:"))
        self.lab_gameinstall_state.setText(_translate("Dialog", "未找到"))
        self.lab_game_path.setText(_translate("Dialog", "TextLabel"))
        self.label_6.setText(_translate("Dialog", "选择完成后请点击OK进入主程序"))
