# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 624)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label.setStyleSheet("font: 9pt \"宋体\";\n"
"color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.lab_savepath = QtWidgets.QLabel(self.centralwidget)
        self.lab_savepath.setGeometry(QtCore.QRect(90, 80, 771, 41))
        self.lab_savepath.setStyleSheet("font: 7pt \"黑体\";color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.lab_savepath.setObjectName("lab_savepath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_2.setStyleSheet("font: 11pt \"Microsoft YaHei\";\n"
"color: #4fe0b0;\n"
"background: transparent;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 61, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lab_geo = QtWidgets.QLabel(self.centralwidget)
        self.lab_geo.setGeometry(QtCore.QRect(100, 150, 51, 31))
        self.lab_geo.setStyleSheet("font: 10pt \"Microsoft YaHei\";\n"
"color: #ff6b6b;\n"
"background: transparent;\n"
"text-align: right;")
        self.lab_geo.setObjectName("lab_geo")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 51, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lab_health = QtWidgets.QLabel(self.centralwidget)
        self.lab_health.setGeometry(QtCore.QRect(100, 180, 51, 31))
        self.lab_health.setStyleSheet("font: 10pt \"Microsoft YaHei\";\n"
"color: #ff6b6b;\n"
"background: transparent;\n"
"text-align: right;")
        self.lab_health.setObjectName("lab_health")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 71, 31))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.lab_maxhelath = QtWidgets.QLabel(self.centralwidget)
        self.lab_maxhelath.setGeometry(QtCore.QRect(100, 210, 51, 31))
        self.lab_maxhelath.setStyleSheet("font: 10pt \"Microsoft YaHei\";\n"
"color: #ff6b6b;\n"
"background: transparent;\n"
"text-align: right;")
        self.lab_maxhelath.setObjectName("lab_maxhelath")
        self.lab_nailDamage = QtWidgets.QLabel(self.centralwidget)
        self.lab_nailDamage.setGeometry(QtCore.QRect(100, 300, 51, 31))
        self.lab_nailDamage.setStyleSheet("font: 10pt \"Microsoft YaHei\";\n"
"color: #ff6b6b;\n"
"background: transparent;\n"
"text-align: right;")
        self.lab_nailDamage.setObjectName("lab_nailDamage")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 300, 71, 31))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 61, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lab_mp = QtWidgets.QLabel(self.centralwidget)
        self.lab_mp.setGeometry(QtCore.QRect(100, 240, 51, 31))
        self.lab_mp.setStyleSheet("font: 10pt \"Microsoft YaHei\";\n"
"color: #ff6b6b;\n"
"background: transparent;\n"
"text-align: right;")
        self.lab_mp.setObjectName("lab_mp")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 61, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lab_maxmp = QtWidgets.QLabel(self.centralwidget)
        self.lab_maxmp.setGeometry(QtCore.QRect(100, 270, 51, 31))
        self.lab_maxmp.setStyleSheet("font: 10pt \"Microsoft YaHei\";\n"
"color: #ff6b6b;\n"
"background: transparent;\n"
"text-align: right;")
        self.lab_maxmp.setObjectName("lab_maxmp")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 330, 81, 31))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.lab_nailupdate = QtWidgets.QLabel(self.centralwidget)
        self.lab_nailupdate.setGeometry(QtCore.QRect(100, 330, 51, 31))
        self.lab_nailupdate.setStyleSheet("font: 10pt \"Microsoft YaHei\";\n"
"color: #ff6b6b;\n"
"background: transparent;\n"
"text-align: right;")
        self.lab_nailupdate.setObjectName("lab_nailupdate")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, -10, 491, 51))
        self.label_11.setStyleSheet("color: #4fe0b0;\n"
"font: 16pt \"Microsoft YaHei\";\n"
"font-weight: bold;\n"
"background: transparent;\n"
"text-shadow: 0 0 10px rgba(79, 224, 176, 0.5);")
        self.label_11.setObjectName("label_11")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(150, 400, 391, 141))
        self.textEdit_log.setStyleSheet("color: rgb(255, 255, 255);")
        self.textEdit_log.setObjectName("textEdit_log")
        self.lineEdit_Geo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Geo.setGeometry(QtCore.QRect(160, 160, 41, 21))
        self.lineEdit_Geo.setStyleSheet("QLineEdit {\n"
"    background: rgba(26, 16, 41, 0.6);\n"
"    color: #e0d0ff;\n"
"    border: 1px solid #4a3a6c;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ffd166;\n"
"    outline: none;\n"
"}")
        self.lineEdit_Geo.setObjectName("lineEdit_Geo")
        self.btn_change_geo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_geo.setGeometry(QtCore.QRect(210, 160, 61, 21))
        self.btn_change_geo.setStyleSheet("QPushButton {\n"
"    background: #a879e6;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #b889f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #9869d6;\n"
"}")
        self.btn_change_geo.setObjectName("btn_change_geo")
        self.lineEdit_Health = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Health.setGeometry(QtCore.QRect(160, 190, 41, 21))
        self.lineEdit_Health.setStyleSheet("QLineEdit {\n"
"    background: rgba(26, 16, 41, 0.6);\n"
"    color: #e0d0ff;\n"
"    border: 1px solid #4a3a6c;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ffd166;\n"
"    outline: none;\n"
"}")
        self.lineEdit_Health.setObjectName("lineEdit_Health")
        self.btn_change_health = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_health.setGeometry(QtCore.QRect(210, 190, 61, 21))
        self.btn_change_health.setStyleSheet("QPushButton {\n"
"    background: #a879e6;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #b889f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #9869d6;\n"
"}")
        self.btn_change_health.setObjectName("btn_change_health")
        self.lineEdit_MaxHelath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MaxHelath.setGeometry(QtCore.QRect(160, 220, 41, 21))
        self.lineEdit_MaxHelath.setStyleSheet("QLineEdit {\n"
"    background: rgba(26, 16, 41, 0.6);\n"
"    color: #e0d0ff;\n"
"    border: 1px solid #4a3a6c;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ffd166;\n"
"    outline: none;\n"
"}")
        self.lineEdit_MaxHelath.setObjectName("lineEdit_MaxHelath")
        self.btn_change_maxhealth = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_maxhealth.setGeometry(QtCore.QRect(210, 220, 61, 21))
        self.btn_change_maxhealth.setStyleSheet("QPushButton {\n"
"    background: #a879e6;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #b889f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #9869d6;\n"
"}")
        self.btn_change_maxhealth.setObjectName("btn_change_maxhealth")
        self.lineEdit_mp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mp.setGeometry(QtCore.QRect(160, 250, 41, 21))
        self.lineEdit_mp.setStyleSheet("QLineEdit {\n"
"    background: rgba(26, 16, 41, 0.6);\n"
"    color: #e0d0ff;\n"
"    border: 1px solid #4a3a6c;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ffd166;\n"
"    outline: none;\n"
"}")
        self.lineEdit_mp.setObjectName("lineEdit_mp")
        self.btn_change_mp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_mp.setGeometry(QtCore.QRect(210, 250, 61, 21))
        self.btn_change_mp.setStyleSheet("QPushButton {\n"
"    background: #a879e6;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #b889f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #9869d6;\n"
"}")
        self.btn_change_mp.setObjectName("btn_change_mp")
        self.lineEdit_MaxMp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MaxMp.setGeometry(QtCore.QRect(160, 280, 41, 21))
        self.lineEdit_MaxMp.setStyleSheet("QLineEdit {\n"
"    background: rgba(26, 16, 41, 0.6);\n"
"    color: #e0d0ff;\n"
"    border: 1px solid #4a3a6c;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ffd166;\n"
"    outline: none;\n"
"}")
        self.lineEdit_MaxMp.setObjectName("lineEdit_MaxMp")
        self.btn_change_maxmp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_maxmp.setGeometry(QtCore.QRect(210, 280, 61, 21))
        self.btn_change_maxmp.setStyleSheet("QPushButton {\n"
"    background: #a879e6;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #b889f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #9869d6;\n"
"}")
        self.btn_change_maxmp.setObjectName("btn_change_maxmp")
        self.lineEdit_nailDamage = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nailDamage.setGeometry(QtCore.QRect(160, 310, 41, 21))
        self.lineEdit_nailDamage.setStyleSheet("QLineEdit {\n"
"    background: rgba(26, 16, 41, 0.6);\n"
"    color: #e0d0ff;\n"
"    border: 1px solid #4a3a6c;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ffd166;\n"
"    outline: none;\n"
"}")
        self.lineEdit_nailDamage.setObjectName("lineEdit_nailDamage")
        self.btn_change_nailDamage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_nailDamage.setGeometry(QtCore.QRect(210, 310, 61, 21))
        self.btn_change_nailDamage.setStyleSheet("QPushButton {\n"
"    background: #a879e6;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #b889f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #9869d6;\n"
"}")
        self.btn_change_nailDamage.setObjectName("btn_change_nailDamage")
        self.lineEdit_nailDamage_update = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nailDamage_update.setGeometry(QtCore.QRect(160, 340, 41, 21))
        self.lineEdit_nailDamage_update.setStyleSheet("QLineEdit {\n"
"    background: rgba(26, 16, 41, 0.6);\n"
"    color: #e0d0ff;\n"
"    border: 1px solid #4a3a6c;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #ffd166;\n"
"    outline: none;\n"
"}")
        self.lineEdit_nailDamage_update.setObjectName("lineEdit_nailDamage_update")
        self.btn_change_nailDamageupdate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_nailDamageupdate.setGeometry(QtCore.QRect(210, 340, 61, 21))
        self.btn_change_nailDamageupdate.setStyleSheet("QPushButton {\n"
"    background: #a879e6;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #b889f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #9869d6;\n"
"}")
        self.btn_change_nailDamageupdate.setObjectName("btn_change_nailDamageupdate")
        self.btn_flash = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flash.setGeometry(QtCore.QRect(310, 240, 81, 31))
        self.btn_flash.setStyleSheet("QPushButton {\n"
"    background: #6bcbff;\n"
"    color: #1a1029;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #8bdbff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #5bc0e0;\n"
"}")
        self.btn_flash.setObjectName("btn_flash")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_14.setStyleSheet("font: 9pt \"宋体\";\n"
"color: rgb(255, 170, 255);")
        self.label_14.setObjectName("label_14")
        self.lab_gamepath = QtWidgets.QLabel(self.centralwidget)
        self.lab_gamepath.setGeometry(QtCore.QRect(100, 40, 731, 41))
        self.lab_gamepath.setStyleSheet("font: 9pt \"黑体\";color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.lab_gamepath.setObjectName("lab_gamepath")
        self.btn_saveas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_saveas.setGeometry(QtCore.QRect(10, 430, 121, 31))
        self.btn_saveas.setStyleSheet("QPushButton {\n"
"    background: #ffd166;\n"
"    color: #1a1029;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ffe186;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #eec156;\n"
"}")
        self.btn_saveas.setObjectName("btn_saveas")
        self.btn_encode = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encode.setGeometry(QtCore.QRect(10, 510, 121, 31))
        self.btn_encode.setStyleSheet("QPushButton {\n"
"    background: #ff6b6b;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ff8b8b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #ee5b5b;\n"
"}")
        self.btn_encode.setObjectName("btn_encode")
        self.btn_openuserdata = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openuserdata.setGeometry(QtCore.QRect(10, 470, 121, 31))
        self.btn_openuserdata.setStyleSheet("QPushButton {\n"
"    background: #ff6b6b;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ff8b8b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #ee5b5b;\n"
"}")
        self.btn_openuserdata.setObjectName("btn_openuserdata")
        self.btn_readsave = QtWidgets.QPushButton(self.centralwidget)
        self.btn_readsave.setGeometry(QtCore.QRect(10, 390, 121, 31))
        self.btn_readsave.setStyleSheet("QPushButton {\n"
"    background: #ff6b6b;\n"
"    color: white;\n"
"    font: 10pt \"Microsoft YaHei\";\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ff8b8b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #ee5b5b;\n"
"}")
        self.btn_readsave.setObjectName("btn_readsave")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "存档位置:"))
        self.lab_savepath.setText(_translate("MainWindow", "Null"))
        self.label_2.setText(_translate("MainWindow", "存档信息："))
        self.label_3.setText(_translate("MainWindow", "Geo吉欧:"))
        self.lab_geo.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "血量:"))
        self.lab_health.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "最大血量:"))
        self.lab_maxhelath.setText(_translate("MainWindow", "0"))
        self.lab_nailDamage.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "骨钉攻击力:"))
        self.label_4.setText(_translate("MainWindow", "当前灵魂:"))
        self.lab_mp.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "最大灵魂:"))
        self.lab_maxmp.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "骨钉升级次数:"))
        self.lab_nailupdate.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Hollow Knight(空洞骑士)存档修改器"))
        self.btn_change_geo.setText(_translate("MainWindow", "修改"))
        self.btn_change_health.setText(_translate("MainWindow", "修改"))
        self.btn_change_maxhealth.setText(_translate("MainWindow", "修改"))
        self.btn_change_mp.setText(_translate("MainWindow", "修改"))
        self.btn_change_maxmp.setText(_translate("MainWindow", "修改"))
        self.btn_change_nailDamage.setText(_translate("MainWindow", "修改"))
        self.btn_change_nailDamageupdate.setText(_translate("MainWindow", "修改"))
        self.btn_flash.setText(_translate("MainWindow", "刷新"))
        self.label_14.setText(_translate("MainWindow", "游戏安装位置:"))
        self.lab_gamepath.setText(_translate("MainWindow", "Null"))
        self.btn_saveas.setText(_translate("MainWindow", "导出原存档"))
        self.btn_encode.setText(_translate("MainWindow", "编译存档文件"))
        self.btn_openuserdata.setText(_translate("MainWindow", "打开userdata.json"))
        self.btn_readsave.setText(_translate("MainWindow", "读取存档"))
